channels:
    - conda-forge
    - nodefaults
dependencies:
    - bioconda::bcftools==1.13
    - conda-forge::datamash==1.7
    - conda-forge::pandas==1.3.0
    - conda-forge::seaborn==0.11.1
    - conda-forge::coreutils==8.31
    - conda-forge::sed==4.8
    - conda-forge::bash==5.0.018
    - conda-forge::gzip==1.10
    - bioconda::plink2==2.00a2.3
    - conda-forge::ipython # for debugging
